# Generated by Django 3.2.6 on 2022-01-10 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_medicine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='buy_price',
            field=models.FloatField(max_length=255),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='sell_price',
            field=models.FloatField(max_length=255),
        ),
    ]
