# Generated by Django 3.2.6 on 2022-01-10 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_auto_20220110_1939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='qty_front',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='qty_instock',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='qty_online',
            field=models.IntegerField(null=True),
        ),
    ]
