# Generated by Django 3.2.6 on 2022-01-10 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_auto_20220110_2209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='buy_price',
            field=models.FloatField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='description',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='medical_typ',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='sell_price',
            field=models.FloatField(max_length=255, null=True),
        ),
    ]
