# Generated by Django 3.2.6 on 2022-01-23 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_auto_20220122_2249'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='medicine',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
