# Generated by Django 3.2.6 on 2022-01-29 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_auto_20220129_1722'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='total',
            new_name='order_total_price',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='item_total_price',
            field=models.FloatField(max_length=255, null=True),
        ),
    ]
