# Generated by Django 3.2.6 on 2022-01-29 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_auto_20220129_1727'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_total_quantity',
            field=models.FloatField(max_length=255, null=True),
        ),
    ]
