# Generated by Django 3.2.6 on 2022-02-09 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0032_alter_medicine_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='buy_price',
            field=models.FloatField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='company_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.company'),
        ),
        migrations.AddField(
            model_name='product',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='medical_typ',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
